[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_rounds = 1000
evm_version="paris"

fs_permissions = [{ access = "read", path = "./broadcast" }, { access = "read", path = "./out" }, { access = "write", path = "./lib" }]

# --chains--
[rpc_endpoints]
bsc = "${RPC_BSC}"
bsctest = "${RPC_BSC_TEST}"

localhost = "${RPC_LOCALHOST}"

# --scans--
[etherscan]
# Binance Smart Chain
bsc = { key = "${BSCSCAN_KEY}", chain = "56" }
bsctest = { key = "${BSCSCAN_KEY}", chain = "97" }

[fuzz]
runs=10000
max_test_rejects=100000

[invariant]
runs=200
depth=150
fail_on_revert=true

# [profile.default.model_checker]
# contracts = { "src/FlamelingToken.sol" = ["FlamelingToken"] }
# engine = 'chc'
# timeout = 10000
# targets = ['assert']
